# Generated by Django 2.1.5 on 2019-04-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geojson',
            name='id',
        ),
        migrations.AlterField(
            model_name='geojson',
            name='location_name',
            field=models.CharField(max_length=1000, primary_key=True, serialize=False),
        ),
    ]
