# Generated by Django 2.1.5 on 2019-04-11 17:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocation', '0002_auto_20190411_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='geojson1',
            fields=[
                ('location_name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('data', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
