# Generated by Django 2.1.5 on 2019-04-11 17:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocation', '0004_auto_20190411_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson1',
            name='data',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
