# Generated by Django 2.1.5 on 2019-04-11 18:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocation', '0007_geojson_data1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson',
            name='data1',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
