# Generated by Django 2.1.5 on 2019-04-11 18:49

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GeoLocation', '0010_auto_20190412_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geojson',
            name='data',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326),
        ),
    ]
